## Joins

In [2]:
import pandas as pd

df_users = pd.DataFrame({'user_id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df_orders = pd.DataFrame({'order_id': [101, 102], 'user_id': [1, 2], 'amount': [250, 450]})
print(df_users)
print(df_orders)

   user_id     name
0        1    Alice
1        2      Bob
2        3  Charlie
   order_id  user_id  amount
0       101        1     250
1       102        2     450

In [4]:
## 4 major joins 
# A. Inner join(default)

pd.merge(df_users , df_orders , on='user_id', how='inner')

   user_id   name  order_id  amount
0        1  Alice       101     250
1        2    Bob       102     450

In [5]:
# B. Left join

pd.merge(df_users , df_orders , on='user_id' , how='left')

   user_id     name  order_id  amount
0        1    Alice     101.0   250.0
1        2      Bob     102.0   450.0
2        3  Charlie       NaN     NaN

In [ ]:
# C. right join
pd.merge(df_users , df_orders , on='user_id' , how='right')

   user_id   name  order_id  amount
0        1  Alice       101     250
1        2    Bob       102     450

In [ ]:
# D. outer join
pd.merge(df_users , df_orders , on='user_id' , how='outer')

   user_id     name  order_id  amount
0        1    Alice     101.0   250.0
1        2      Bob     102.0   450.0
2        3  Charlie       NaN     NaN

 _Pro-Tip for Messy Data: If your joining columns have different names in the two datasets (e.g., user_id in the left table and customer_id in the right), use left_on and right_on:
pd.merge(df_users, df_orders, left_on='user_id', right_on='customer_id', how='left')_

In [12]:
#SQL Equivalent: Joining two tables on their Primary Keys.
#When to use it: When your DataFrames already have the ID column set as their index.

df_users_idx = df_users.set_index('user_id')
df_orders_idx = df_orders.set_index('user_id')
print(df_users_idx)

result = df_users_idx.join(df_orders_idx , how='inner')
print(result)

            name
user_id
1          Alice
2            Bob
3        Charlie
          name  order_id  amount
user_id
1        Alice       101     250
2          Bob       102     450