## DataFrame

In [11]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [12]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [13]:
df.head(2) # return starting 2 values

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [14]:
df.tail(4) # return last 4 values

      Name   Age Department   Salary
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [15]:
#loc and iloc 

print(df.iloc[1:3])
print(df.iloc[1:3 , :2])

# from all this col i want only dept salary
df.loc[1:3 , ["Age" , "Department"]] # this indexing inculde start and stop both

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
      Name   Age
1      Bob  30.0
2  Charlie  35.0

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [16]:
df[['Age' , 'Department']]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [17]:
print(df.drop("Age" , axis=1, inplace = True ))
print(df)

None
      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [18]:
df.shape

(6, 3)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Salary      5 non-null      float64
dtypes: float64(1), str(2)
memory usage: 276.0 bytes

In [20]:
df.describe()

             Salary
count      5.000000
mean   58400.000000
std     8532.291603
min    50000.000000
25%    50000.000000
50%    60000.000000
75%    62000.000000
max    70000.000000

In [21]:
# Broadcasting

df['Salary'] = df['Salary'] + 5000
print(df['Salary'])

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [22]:
#rename column

df.rename(columns = {"Department": "Dept"} , inplace = True)
df

      Name     Dept   Salary
0    Alice       HR  55000.0
1      Bob       IT  65000.0
2  Charlie  Finance  75000.0
3    David       IT  67000.0
4      Eve       HR      NaN
5    Alice       HR  55000.0

In [23]:
#unique data
print(df["Salary"].unique())

#counts
df['Dept'].value_counts()

[55000. 65000. 75000. 67000.    nan]

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [24]:
df["Promoted Salary"] = df["Salary"] * 10
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  55000.0         550000.0

### NULL values( Cleaning data )

In [25]:
df.isnull().sum()

Name               0
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [26]:
df.dropna(how = "all") #if all the values in any row are null then we drop

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  55000.0         550000.0

In [27]:
df.dropna(how = "any") #if any values in any row are null then drop that row
# here as not used inplace original df is intect

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
5    Alice       HR  55000.0         550000.0

In [28]:
# to fill null value 
df.fillna(0)

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR      0.0              0.0
5    Alice       HR  55000.0         550000.0

In [29]:
#to fill null value with mean
#df["Age"].fillna(df["Age"].mean())

df["Salary"].fillna(df["Salary"].median())

df["Salary"].ffill() # forward fill
df["Salary"].bfill() # backward fill

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    55000.0
5    55000.0
Name: Salary, dtype: float64

In [30]:
df["Name"] = df["Name"].replace('Charlie' , "Rose")
df

    Name     Dept   Salary  Promoted Salary
0  Alice       HR  55000.0         550000.0
1    Bob       IT  65000.0         650000.0
2   Rose  Finance  75000.0         750000.0
3  David       IT  67000.0         670000.0
4    Eve       HR      NaN              NaN
5  Alice       HR  55000.0         550000.0

### Duplicates

In [31]:
df_dup = df[df.duplicated()]
df_dup

    Name Dept   Salary  Promoted Salary
5  Alice   HR  55000.0         550000.0

In [32]:
df_dup = df[df.duplicated(keep = "last")]
df_dup

    Name Dept   Salary  Promoted Salary
0  Alice   HR  55000.0         550000.0

In [33]:
df = df.drop_duplicates()
df

    Name     Dept   Salary  Promoted Salary
0  Alice       HR  55000.0         550000.0
1    Bob       IT  65000.0         650000.0
2   Rose  Finance  75000.0         750000.0
3  David       IT  67000.0         670000.0
4    Eve       HR      NaN              NaN

In [34]:
#lambda func

df['Promoted Salary'] = df['Promoted Salary'].apply(lambda x : x/10 if x > 650000 else x)
df

    Name     Dept   Salary  Promoted Salary
0  Alice       HR  55000.0         550000.0
1    Bob       IT  65000.0         650000.0
2   Rose  Finance  75000.0          75000.0
3  David       IT  67000.0          67000.0
4    Eve       HR      NaN              NaN

In [35]:

df['Name'] = df['Name'].replace('Alice' , 'Alice_fernandes')
df

              Name     Dept   Salary  Promoted Salary
0  Alice_fernandes       HR  55000.0         550000.0
1              Bob       IT  65000.0         650000.0
2             Rose  Finance  75000.0          75000.0
3            David       IT  67000.0          67000.0
4              Eve       HR      NaN              NaN

In [36]:
name = "Alice_fernandes"
df['first_name' , 'last_name'] = df["Name"].str.split("_")
df

              Name     Dept   Salary  Promoted Salary (first_name, last_name)
0  Alice_fernandes       HR  55000.0         550000.0      [Alice, fernandes]
1              Bob       IT  65000.0         650000.0                   [Bob]
2             Rose  Finance  75000.0          75000.0                  [Rose]
3            David       IT  67000.0          67000.0                 [David]
4              Eve       HR      NaN              NaN                   [Eve]

In [ ]:
# apply and lambda

def multiplying_salary(x):
    return x*2

df["Salary"] = df["Salary"].apply(multiplying_salary)
df

              Name     Dept    Salary  Promoted Salary (first_name, last_name)
0  Alice_fernandes       HR  110000.0         550000.0      [Alice, fernandes]
1              Bob       IT  130000.0         650000.0                   [Bob]
2             Rose  Finance  150000.0          75000.0                  [Rose]
3            David       IT  134000.0          67000.0                 [David]
4              Eve       HR       NaN              NaN                   [Eve]

In [38]:
df["Salary"] = df["Salary"].apply(lambda x: x*2)
df

              Name     Dept    Salary  Promoted Salary (first_name, last_name)
0  Alice_fernandes       HR  220000.0         550000.0      [Alice, fernandes]
1              Bob       IT  260000.0         650000.0                   [Bob]
2             Rose  Finance  300000.0          75000.0                  [Rose]
3            David       IT  268000.0          67000.0                 [David]
4              Eve       HR       NaN              NaN                   [Eve]