### Data Wrangling:
- Data Gathering
- Data Accessing
- Data Cleaning

_Data Gathered in the form csv file_

### Types of Unclean data:
- Dirty data : data with quality issues like ( missing values, dupplicates, corrupt data, inaccurate data)
- Messy data : data with structural problem
  - Tidy data has following properties:
    - Each observation forms a row
    - each variable forms a column
    - each observational unit forms a table

In [91]:
import pandas as pd

audible = pd.read_csv("D:/VScode_work/AI-ML-journey-2026/Data/audible_uncleaned.csv")
audible

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

### Summary of dataset

1. This dataset is about to understand how audiobook industry growing over years.From authors of audiobooks to release dates, the data represents the important details of audiobooks from _1998 till 2025 (pre-planned releases)_

2. Column descriptions
   - Table - `audible`
       - name : name of the audiobook
       - author : name of the author
       - narrator : narrator of audiobook
       - time : duration of audiobook
       - releasedate : when audiobook is released
       - language : language of audiobook
       - stars : no. of stars audiobook received and total rating 
       - price : price of audiobook

Types of assessment:
  - There are two types of assessment styles
       - Manual: by looking at data manually
       - Programmatic: by using pandas functions info() , describe() or sample()

Steps in Assessment:
   1. Discover
   2. Document

### Issues in dataset

Table - `audible`
   - Unnecessarily 'Writtenby:' is written in author column `validity`
   - Unnecessarily 'Narratedby:' is written in narrator column `validity`
   - in time column , change the duration written format in complete minutes or seconds `validity`
   - in language column, some languages first letter is capitalized or some have small `consistency`
   - Stars format is wrong , remove 'out of 5' `validity`
   - Price column contain mixed format of prices in int and decimal `validity`
   - Every column is of type str only `accuracy`
   - 'Not rated yet' used in stars column `validity`
   - duplicate entries with same name , author , narrator , date , price around 404 `accuracy`
   
   - Rating is combined in stars column , need to separate `messy data`

Additional info :

  - Duplicate Analysis:
Approximately 44 records shared the same 'name' , 'author' , 'narrator' , 'releasedate' , 'language' , 'price' , 'stars'.
Since no unique identifier was available and it could not be confirmed whether these represented true duplicates or multiple editions/listings, the records were retained for further domain verification.

### Automatic assessment
  - head and tail
  - sample
  - info
  - isnull
  - duplicate
  - describe

In [92]:
audible.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  str
 1   author       87489 non-null  str
 2   narrator     87489 non-null  str
 3   time         87489 non-null  str
 4   releasedate  87489 non-null  str
 5   language     87489 non-null  str
 6   stars        87489 non-null  str
 7   price        87489 non-null  str
dtypes: str(8)
memory usage: 5.3 MB

In [93]:
audible.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

In [94]:
audible.sample()

,name,author,narrator,time,releasedate,language,stars,price
31454,The Bliss List,Writtenby:J.P.Hansen,Narratedby:J.P.Hansen,4 hrs and 56 mins,16-05-13,English,Not rated yet,586.00

In [95]:
audible.tail()

,name,author,narrator,time,releasedate,language,stars,price
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [96]:
audible.isnull().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
dtype: int64

In [97]:
audible[audible.duplicated(subset =['name' , 'author' , 'narrator'])]

,name,author,narrator,time,releasedate,language,stars,price
18,Merlin Mission Collection,Writtenby:MaryPopeOsborne,Narratedby:MaryPopeOsborne,10 hrs and 18 mins,02-05-17,English,5 out of 5 stars11 ratings,"1,256.00"
54,Merlin Mission Collection,Writtenby:MaryPopeOsborne,Narratedby:MaryPopeOsborne,13 hrs and 24 mins,02-05-17,English,5 out of 5 stars8 ratings,"1,256.00"
1882,Egg Marks the Spot,Writtenby:AmyTimberlake,Narratedby:MichaelBoatman,3 hrs and 54 mins,14-09-21,English,Not rated yet,398.00
2162,Fish,Writtenby:LisaJ.Amstutz,Narratedby:anonymous,18 mins,23-02-22,English,Not rated yet,93.00
2244,The Snail and the Whale,Writtenby:JuliaDonaldson,Narratedby:ImeldaStaunton,22 mins,22-06-21,English,Not rated yet,251.00
...,...,...,...,...,...,...,...,...
86656,Venice,Writtenby:JanMorris,Narratedby:SebastianComberti,5 hrs and 16 mins,09-08-10,English,Not rated yet,668.00
86725,Audiowalk Berlin,Writtenby:TaufigKhalil,Narratedby:TaufigKhalil,1 hr and 12 mins,01-06-05,german,Not rated yet,334.00
86746,City Surf,Writtenby:CitySurf,Narratedby:uncredited,32 mins,23-10-07,English,Not rated yet,234.00
86747,City Surf,Writtenby:CitySurf,Narratedby:uncredited,52 mins,23-10-07,English,Not rated yet,234.00
86749,City Surf,Writtenby:CitySurf,Narratedby:uncredited,40 mins,23-10-07,English,Not rated yet,234.00

Order of severity:
Completeness < Validity < accuracy < consistency

Data cleaning order:
   1. completeness
   2. messy data
   3. validity
   4. accuracy
   5. consistency

Steps involved in data cleaning:
  1. Define 
  2. Code
  3. Test

In [98]:
#Always use copy of your dataframe for data cleaning
audible_df1 = audible.copy()

Define:
  1. Separate rating from stars to new column using regex

In [99]:
import re

audible_df1[['Stars' , 'Rating']] = audible_df1['stars'].str.extract(r'(\d+) out of 5 stars(\d+) ratings')

audible_df1['Stars'] = audible_df1['Stars'].astype(float)
audible_df1['Rating'] = audible_df1['Rating'].astype('Int64')


audible_df1.loc[audible_df1['stars'].str.contains("Not rated yet", na =False) , ['Stars' , 'Rating']] = [None , 0]

In [100]:
audible_df1

,name,author,narrator,time,releasedate,language,stars,price,Stars,Rating
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,5.0,34
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,5.0,41
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,5.0,38
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,5.0,181
...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00,NaN,0
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00,NaN,0
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00,NaN,0
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00,NaN,0
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00,NaN,0

Define: 
 1. filling rating null values with zero
 2. change duration in time column to complete min format 
 3. remove writtenby: and narratedby:
 4. can price column type to decimal

In [101]:
audible_df1['Rating'] = audible_df1['Rating'].fillna(0)
audible_df1['Rating'].isnull().any()

np.False_

In [102]:
def convert_to_minutes(text):
    match = re.search(r'(\d+)\s*hrs?\s*and\s*(\d+)\s*mins?' , text)
    if match:
        hours = int(match.group(1))
        mins = int(match.group(2))
        return hours*60 + mins
    return None

audible_df1['time'] = audible_df1['time'].apply(convert_to_minutes)

In [103]:
audible_df1

,name,author,narrator,time,releasedate,language,stars,price,Stars,Rating
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,140.0,04-08-08,English,5 out of 5 stars34 ratings,468.00,5.0,34
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,788.0,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,5.0,41
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,123.0,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,5.0,38
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,676.0,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,NaN,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,5.0,181
...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,454.0,09-03-17,English,Not rated yet,596.00,NaN,0
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,607.0,21-02-17,English,Not rated yet,820.00,NaN,0
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,1144.0,30-12-16,English,Not rated yet,938.00,NaN,0
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,248.0,23-02-11,English,Not rated yet,680.00,NaN,0
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,361.0,07-03-17,English,Not rated yet,569.00,NaN,0

In [105]:
#remove "Writtenby:" from author column
audible_df1['author'] = audible_df1['author'].str.replace(r'Writtenby:','', regex=True)

In [ ]:
audible_df1

,name,author,narrator,time,releasedate,language,stars,price,Stars,Rating
0,Geronimo Stilton #11 & #12,GeronimoStilton,Narratedby:BillLobely,140.0,04-08-08,English,5 out of 5 stars34 ratings,468.00,5.0,34
1,The Burning Maze,RickRiordan,Narratedby:RobbieDaymond,788.0,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,5.0,41
2,The Deep End,JeffKinney,Narratedby:DanRussell,123.0,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,5.0,38
3,Daughter of the Deep,RickRiordan,Narratedby:SoneelaNankani,676.0,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,Narratedby:JesseBernstein,NaN,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,5.0,181
...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,Narratedby:ChrisStewart,454.0,09-03-17,English,Not rated yet,596.00,NaN,0
87485,The Alps,StephenO'Shea,Narratedby:RobertFass,607.0,21-02-17,English,Not rated yet,820.00,NaN,0
87486,The Innocents Abroad,MarkTwain,Narratedby:FloGibson,1144.0,30-12-16,English,Not rated yet,938.00,NaN,0
87487,A Sentimental Journey,LaurenceSterne,Narratedby:AntonLesser,248.0,23-02-11,English,Not rated yet,680.00,NaN,0
87488,Havana,MarkKurlansky,Narratedby:FleetCooper,361.0,07-03-17,English,Not rated yet,569.00,NaN,0

In [106]:
# remove "Narratedby:" from narrator column
audible_df1['narrator'] = audible_df1['narrator'].str.replace(r'Narratedby:', '', regex=True)
audible_df1

,name,author,narrator,time,releasedate,language,stars,price,Stars,Rating
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140.0,04-08-08,English,5 out of 5 stars34 ratings,468.00,5.0,34
1,The Burning Maze,RickRiordan,RobbieDaymond,788.0,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,5.0,41
2,The Deep End,JeffKinney,DanRussell,123.0,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,5.0,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676.0,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,NaN,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,5.0,181
...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,454.0,09-03-17,English,Not rated yet,596.00,NaN,0
87485,The Alps,StephenO'Shea,RobertFass,607.0,21-02-17,English,Not rated yet,820.00,NaN,0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144.0,30-12-16,English,Not rated yet,938.00,NaN,0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,248.0,23-02-11,English,Not rated yet,680.00,NaN,0
87488,Havana,MarkKurlansky,FleetCooper,361.0,07-03-17,English,Not rated yet,569.00,NaN,0

In [107]:
audible_df1 = audible_df1.rename(columns={'time': 'Time (min)'})

In [108]:
audible_df1 = audible_df1.rename(columns={'name': 'Name'})
audible_df1 = audible_df1.rename(columns={'author': 'Author'})
audible_df1 = audible_df1.rename(columns={'narrator': 'Narrator'})
audible_df1 = audible_df1.rename(columns={'releasedate': 'Release Date'})
audible_df1 = audible_df1.rename(columns={'language': 'Language'})
audible_df1 = audible_df1.rename(columns={'price': 'Price'})
audible_df1 = audible_df1.drop(columns=['stars'])

In [109]:
audible_df1

,Name,Author,Narrator,Time (min),Release Date,Language,Price,Stars,Rating
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140.0,04-08-08,English,468.00,5.0,34
1,The Burning Maze,RickRiordan,RobbieDaymond,788.0,01-05-18,English,820.00,5.0,41
2,The Deep End,JeffKinney,DanRussell,123.0,06-11-20,English,410.00,5.0,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676.0,05-10-21,English,615.00,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,NaN,13-01-10,English,820.00,5.0,181
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,454.0,09-03-17,English,596.00,NaN,0
87485,The Alps,StephenO'Shea,RobertFass,607.0,21-02-17,English,820.00,NaN,0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144.0,30-12-16,English,938.00,NaN,0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,248.0,23-02-11,English,680.00,NaN,0
87488,Havana,MarkKurlansky,FleetCooper,361.0,07-03-17,English,569.00,NaN,0

In [110]:
audible_df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          87489 non-null  str
 1   Author        87489 non-null  str
 2   Narrator      87489 non-null  str
 3   Time (min)    72740 non-null  float64
 4   Release Date  87489 non-null  str
 5   Language      87489 non-null  str
 6   Price         87489 non-null  str
 7   Stars         9211 non-null   float64
 8   Rating        87489 non-null  Int64
dtypes: Int64(1), float64(2), str(6)
memory usage: 6.1 MB

In [111]:
audible_df1['Price'] = audible_df1['Price'].str.replace(',' , '' , regex=False).replace('Free' , '0').astype(float)

In [112]:
audible_df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          87489 non-null  str
 1   Author        87489 non-null  str
 2   Narrator      87489 non-null  str
 3   Time (min)    72740 non-null  float64
 4   Release Date  87489 non-null  str
 5   Language      87489 non-null  str
 6   Price         87489 non-null  float64
 7   Stars         9211 non-null   float64
 8   Rating        87489 non-null  Int64
dtypes: Int64(1), float64(3), str(5)
memory usage: 6.1 MB

In [114]:
audible_df1.sample()

,Name,Author,Narrator,Time (min),Release Date,Language,Price,Stars,Rating
74916,Billionaire's Burlesque Club (German edition),RebeccaBaker,"PaulHilliger,JuliaRost",330.0,27-07-21,german,434.0,NaN,0

Define
  1. Some language first letter is capital or some has small , change it to capital letter
  2. change the datatype of release date

In [115]:
audible_df1['Language'] = audible_df1['Language'].str.title()
audible_df1

,Name,Author,Narrator,Time (min),Release Date,Language,Price,Stars,Rating
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140.0,04-08-08,English,468.0,5.0,34
1,The Burning Maze,RickRiordan,RobbieDaymond,788.0,01-05-18,English,820.0,5.0,41
2,The Deep End,JeffKinney,DanRussell,123.0,06-11-20,English,410.0,5.0,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676.0,05-10-21,English,615.0,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,NaN,13-01-10,English,820.0,5.0,181
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,454.0,09-03-17,English,596.0,NaN,0
87485,The Alps,StephenO'Shea,RobertFass,607.0,21-02-17,English,820.0,NaN,0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144.0,30-12-16,English,938.0,NaN,0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,248.0,23-02-11,English,680.0,NaN,0
87488,Havana,MarkKurlansky,FleetCooper,361.0,07-03-17,English,569.0,NaN,0

In [127]:
audible_df1.sample()

,Name,Author,Narrator,Time (min),Release Date,Language,Price,Stars,Rating
81484,Krumme Touren 2,RenateJust,RenateJust,76.0,28-12-09,German,367.0,NaN,0

In [131]:
audible_df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          87489 non-null  str
 1   Author        87489 non-null  str
 2   Narrator      87489 non-null  str
 3   Time (min)    72740 non-null  float64
 4   Release Date  87489 non-null  str
 5   Language      87489 non-null  str
 6   Price         87489 non-null  float64
 7   Stars         9211 non-null   float64
 8   Rating        87489 non-null  Int64
dtypes: Int64(1), float64(3), str(5)
memory usage: 6.1 MB

In [135]:
# Convert to datetime, then extract only the date
audible_df1['Release Date'] = pd.to_datetime(audible_df1['Release Date'] , errors='coerce').dt.date

In [138]:
audible_df1

,Name,Author,Narrator,Time (min),Release Date,Language,Price,Stars,Rating
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140.0,2008-04-08,English,468.0,5.0,34
1,The Burning Maze,RickRiordan,RobbieDaymond,788.0,2018-01-05,English,820.0,5.0,41
2,The Deep End,JeffKinney,DanRussell,123.0,2020-06-11,English,410.0,5.0,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676.0,2021-05-10,English,615.0,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,NaN,2010-01-13,English,820.0,5.0,181
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,454.0,2017-09-03,English,596.0,NaN,0
87485,The Alps,StephenO'Shea,RobertFass,607.0,2017-02-21,English,820.0,NaN,0
87486,The Innocents Abroad,MarkTwain,FloGibson,1144.0,2016-12-30,English,938.0,NaN,0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,248.0,2011-02-23,English,680.0,NaN,0
87488,Havana,MarkKurlansky,FleetCooper,361.0,2017-07-03,English,569.0,NaN,0

In [141]:
audible[audible.duplicated(subset =['name' , 'author' , 'narrator' , 'releasedate' , 'language' , 'price' , 'stars'])].shape

(44, 8)

In [142]:
print("Original Shape:", audible.shape)
print("Cleaned Shape:", audible_df1.shape)
print(audible_df1.info())
audible_df1.head()

Original Shape: (87489, 8)
Cleaned Shape: (87489, 9)
<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          87489 non-null  str
 1   Author        87489 non-null  str
 2   Narrator      87489 non-null  str
 3   Time (min)    72740 non-null  float64
 4   Release Date  87489 non-null  object
 5   Language      87489 non-null  str
 6   Price         87489 non-null  float64
 7   Stars         9211 non-null   float64
 8   Rating        87489 non-null  Int64
dtypes: Int64(1), float64(3), object(1), str(4)
memory usage: 6.1+ MB
None

,Name,Author,Narrator,Time (min),Release Date,Language,Price,Stars,Rating
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,140.0,2008-04-08,English,468.0,5.0,34
1,The Burning Maze,RickRiordan,RobbieDaymond,788.0,2018-01-05,English,820.0,5.0,41
2,The Deep End,JeffKinney,DanRussell,123.0,2020-06-11,English,410.0,5.0,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,676.0,2021-05-10,English,615.0,5.0,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,NaN,2010-01-13,English,820.0,5.0,181